### ISSUE TITLE
posts are not diplayed.

### ISSUE THREAD

**Issue by estelll** [mmistakes/minimal-mistakes#1512]
- [ ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [x] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 4.9.0** 
- **Jekyll version:3.7.2**
- **GitHub Pages hosted: no** 
- **Operating system: win 10** 

---

## Expected behavior

Posts displayed on the sites.

## Steps to reproduce the behavior

I follow the tutorial on https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/ and build a local site from scratch by command line  'jekyll new test.blog'.
When I ran 'bundle exec jekyll serve', it successfully ran on 127.0.0.1:4000, but I found that **There is no post presented on the site even if there is a default .markdown in _posts dir**
I changed the 'layout:post' into 'layout:single'  as described in tutorial. I don't know why this happened.

And I used the GitHub Pages Method at the same time and push the repository into my github. Still there is no post shown on the site.

**Comment by mmistakes** [comment]
It appears you have the homepage misconfigured.

Your post shows up fine:

https://estelll.github.io/jekyll/update/2018/01/31/welcome-to-jekyll.html

**Comment by mmistakes** [comment]
Please consult the home layout documentation. You need to configure Jekyll's pagination for it to display posts on the index page.

https://mmistakes.github.io/minimal-mistakes/docs/layouts/#home-page-layout

**Comment by mmistakes** [comment]
1. Rename `index.md` to `index.html`
2. Add pagination settings to _config.yml
3. Verify jekyll-seo-tag plugin is installed

**Comment by estelll** [comment]
@mmistakes solved. Thank u so much~

**Comment by estelll** [comment]
@mmistakes Ah, it worked locally on my computer as I renamed index.md to index.html and added pagination settings. But when I pushed a github pages version into my repository, posts still disappeared! 
In github page version, I just replaced `gem "jekyll"` with `gem 'github-pages',group::jekyll_plugins` in Gemfile, and replaced `theme: "minimal-mistakes-jekyll"` with remote_theme: `mmistakes/minimal-mistakes`. Then I `bundle update`, and `bundle`.
As I wanted to have a look at the site locally I typed in the command `bundle exec jekyll serve` . But it printed out an error `Dependency Error: Yikes! It looks like you don't have jekyll-remote-theme or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'Could not open library 'libcurl': �Ҳ���ָ����ģ�顣 . Could not open library 'libcurl.dll': �Ҳ���ָ����ģ�顣 . Could not open library 'libcurl.so.4': �Ҳ���ָ����ģ�顣 . Could not open library 'libcurl.so.4.dll': �Ҳ���ָ����ģ�顣 ' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!` I'm sure I've installed remote-theme . Then I insert  `gem "jekyll-remote-them"` into `group :jekyll_plugins do` in Gemfile. As a result, the error changed to `Could not open library 'libcurl.dll'`and so on(all of them are related to 'libcurl').  
TAT...

Sorry to bother you such much~

**Comment by mmistakes** [comment]
This is a known issue with **jekyll-remote-theme** and Windows... it has nothing to do with my theme. In fact I've had the same problem trying to use it on Windows to test locally.

You might want to chime in here since you're not the only one with the issue.

https://github.com/benbalter/jekyll-remote-theme/issues/18

**Comment by mmistakes** [comment]
Also the reason it's still not working on GitHub Pages is you have both `index.html` and `index.md` in the root of your project. That's confusing Jekyll.

Remove the `index.md` file and it should work.

**Comment by estelll** [comment]
@mmistakes  yeah~~ I'm so sorry that I renamed the index.md into index.html in local repository and I forgot that I have pushed the former version with index.md before.
Finally it worked!
And I have to say it is indeed a great work!~ Thank u so much!

**Comment by estelll** [comment]
@mmistakes  yeah~~ I'm so sorry that I renamed the index.md into index.html in local repository and I forgot that I have pushed the former version with index.md before.
Finally it worked!
And I have to say it is indeed a great work!~ Thank u so much!

**Comment by estelll** [comment]
@mmistakes  I'm sorry to bother you again for I did not find any tutorial about how to make my posts grouped by category like a demo page shown in your website. 
I don't know where else to ask you this question >.<  Sorry..

**Comment by mmistakes** [comment]
Have a thorough read through the docs and README, I mention a few times all of the demo pages are in the `/docs` folder, where you can see the source code to copy into your own project.

https://github.com/mmistakes/minimal-mistakes/tree/master/docs/_pages

**Comment by estelll** [comment]
@mmistakes Thank u~
I've read the README and the theme's documentation thoroughly. And I followed the tutorial to copy the category_archive.html to /category/index.html and I can found the page on which my posts are grouped by categories. 
But what I really want to know is  how to make posts grouped by category on the home page instead of showing the recent posts. Should I replace the index.html on the root dir by category_archive.html?

**Comment by jenil04** [comment]
I'm getting the following error: (@mmistakes )
remote: Permission to mmistakes/minimal-mistakes.git denied to jenil04.
fatal: unable to access 'https://github.com/mmistakes/minimal-mistakes.git/': The requested URL returned error: 403

Please help. Thank you

**Comment by aymanshams07** [comment]
> * Rename `index.md` to `index.html`
> * Add pagination settings to _config.yml
> * Verify jekyll-paginate plugin is installed

followed all these steps, still getting "remote: Permission to mmistakes/minimal-mistakes.git denied to aymanshams07.
fatal: unable to access 'https://github.com/mmistakes/minimal-mistakes.git/': The requested URL returned error: 403" when i try to push

**Comment by mmistakes** [comment]
If you’re pushing to https://github.com/mmistakes/minimal-mistakes.git/ then that’s your problem. Update your `remote` repo to yours. You can’t push to my repo.
